# External Secrets Operator Configuration for SIEM-SOAR Platform
# Syncs secrets from external providers (GCP Secret Manager, AWS Secrets Manager, Vault)

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
# HelmRelease for External Secrets Operator
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: "0.9.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
---
# ClusterSecretStore for GCP Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: siem-soar-platform  # Replace with your GCP project ID
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast3
          clusterName: siem-soar-prod
          clusterProjectID: siem-soar-platform
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# ClusterSecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# ClusterSecretStore for HashiCorp Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# ExternalSecret for ClickHouse credentials (GCP)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-secret
  namespace: siem-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: clickhouse-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: siem-soar-platform
  data:
    - secretKey: password
      remoteRef:
        key: siem-clickhouse-password
        version: latest
    - secretKey: username
      remoteRef:
        key: siem-clickhouse-username
        version: latest
---
# ExternalSecret for PostgreSQL credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: siem-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: siem-postgresql-password
        version: latest
---
# ExternalSecret for Redis credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: siem-data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: siem-redis-password
        version: latest
---
# ExternalSecret for JWT keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gateway-jwt-secret
  namespace: siem-services
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: gateway-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: public-key
      remoteRef:
        key: siem-jwt-public-key
        version: latest
    - secretKey: private-key
      remoteRef:
        key: siem-jwt-private-key
        version: latest
---
# ExternalSecret for TI Feed API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ti-feeds-secret
  namespace: siem-services
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: ti-feeds-secret
    creationPolicy: Owner
  data:
    - secretKey: misp-api-key
      remoteRef:
        key: siem-misp-api-key
        version: latest
    - secretKey: otx-api-key
      remoteRef:
        key: siem-alienvault-otx-key
        version: latest
    - secretKey: kisa-api-key
      remoteRef:
        key: siem-kisa-api-key
        version: latest
---
# ServiceAccount for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # GCP Workload Identity
    iam.gke.io/gcp-service-account: external-secrets@siem-soar-platform.iam.gserviceaccount.com
    # AWS IRSA
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/external-secrets-role
