"""Summary templates for different incident types and audiences."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from pydantic import Field

from common.models import BaseModel


class TemplateType(str, Enum):
    """Types of summary templates."""

    EXECUTIVE = "executive"
    TECHNICAL = "technical"
    SOC_ANALYST = "soc_analyst"
    INCIDENT_RESPONSE = "incident_response"
    COMPLIANCE = "compliance"
    THREAT_INTEL = "threat_intel"


class IncidentCategory(str, Enum):
    """Incident categories for template selection."""

    MALWARE = "malware"
    PHISHING = "phishing"
    DATA_BREACH = "data_breach"
    INTRUSION = "intrusion"
    DOS = "dos"
    INSIDER_THREAT = "insider_threat"
    RANSOMWARE = "ransomware"
    APT = "apt"
    GENERAL = "general"


class SummaryTemplate(BaseModel):
    """Template for generating summaries."""

    name: str = Field(description="Template name")
    template_type: TemplateType = Field(description="Template type")
    incident_category: IncidentCategory = Field(description="Applicable incident category")
    language: str = Field(default="en", description="Template language")

    # Template sections
    header_template: str = Field(description="Header/title template")
    executive_summary_template: str = Field(description="Executive summary template")
    detailed_summary_template: str = Field(description="Detailed summary template")
    findings_template: str = Field(description="Findings section template")
    ioc_template: str = Field(description="IOC section template")
    timeline_template: str = Field(description="Timeline section template")
    recommendations_template: str = Field(description="Recommendations template")
    footer_template: str = Field(default="", description="Footer template")

    # Metadata
    required_fields: list[str] = Field(default_factory=list)
    optional_sections: list[str] = Field(default_factory=list)


# Default English templates
EXECUTIVE_TEMPLATE_EN = SummaryTemplate(
    name="Executive Summary",
    template_type=TemplateType.EXECUTIVE,
    incident_category=IncidentCategory.GENERAL,
    language="en",
    header_template="""
# Security Incident Report: {incident_id}
**Date:** {generated_date}
**Severity:** {severity}
**Status:** {status}
""",
    executive_summary_template="""
## Executive Summary

{executive_summary}

**Key Impact:**
- Affected Systems: {affected_count}
- Duration: {duration}
- Business Impact: {business_impact}
""",
    detailed_summary_template="""
## Incident Overview

{detailed_summary}
""",
    findings_template="""
## Key Findings

{findings_list}
""",
    ioc_template="""
## Indicators of Compromise

| Type | Value | Context |
|------|-------|---------|
{ioc_table}
""",
    timeline_template="""
## Timeline

{timeline_entries}
""",
    recommendations_template="""
## Recommended Actions

{recommendations_list}

**Priority Actions:**
1. {priority_action_1}
2. {priority_action_2}
""",
    footer_template="""
---
*Report generated by Security Copilot AI*
*Confidence: {confidence}%*
""",
    required_fields=["incident_id", "severity", "executive_summary"],
    optional_sections=["ioc_template", "timeline_template"],
)


TECHNICAL_TEMPLATE_EN = SummaryTemplate(
    name="Technical Analysis",
    template_type=TemplateType.TECHNICAL,
    incident_category=IncidentCategory.GENERAL,
    language="en",
    header_template="""
# Technical Analysis Report
**Incident ID:** {incident_id}
**Analysis Date:** {generated_date}
**Analyst:** {analyst}
**Classification:** {severity} - {attack_pattern}
""",
    executive_summary_template="""
## Summary
{executive_summary}
""",
    detailed_summary_template="""
## Technical Details

### Attack Vector
{attack_vector}

### Affected Systems
{affected_systems}

### Technical Analysis
{detailed_summary}

### MITRE ATT&CK Mapping
{mitre_mapping}
""",
    findings_template="""
## Technical Findings

{findings_list}

### Evidence
{evidence_list}
""",
    ioc_template="""
## Indicators of Compromise (IOCs)

### Network Indicators
{network_iocs}

### File Indicators
{file_iocs}

### Behavioral Indicators
{behavioral_iocs}
""",
    timeline_template="""
## Attack Timeline

```
{timeline_ascii}
```

### Detailed Timeline
{timeline_entries}
""",
    recommendations_template="""
## Remediation Steps

### Immediate Actions
{immediate_actions}

### Short-term Remediation
{short_term_actions}

### Long-term Improvements
{long_term_actions}
""",
    required_fields=["incident_id", "detailed_summary", "attack_pattern"],
    optional_sections=["mitre_mapping"],
)


# Korean templates
EXECUTIVE_TEMPLATE_KO = SummaryTemplate(
    name="경영진 보고서",
    template_type=TemplateType.EXECUTIVE,
    incident_category=IncidentCategory.GENERAL,
    language="ko",
    header_template="""
# 보안 인시던트 보고서: {incident_id}
**일자:** {generated_date}
**심각도:** {severity}
**상태:** {status}
""",
    executive_summary_template="""
## 경영진 요약

{executive_summary}

**주요 영향:**
- 영향받은 시스템: {affected_count}
- 지속 시간: {duration}
- 비즈니스 영향: {business_impact}
""",
    detailed_summary_template="""
## 인시던트 개요

{detailed_summary}
""",
    findings_template="""
## 주요 발견사항

{findings_list}
""",
    ioc_template="""
## 침해 지표 (IOC)

| 유형 | 값 | 컨텍스트 |
|------|-------|---------|
{ioc_table}
""",
    timeline_template="""
## 타임라인

{timeline_entries}
""",
    recommendations_template="""
## 권장 조치

{recommendations_list}

**우선 조치:**
1. {priority_action_1}
2. {priority_action_2}
""",
    footer_template="""
---
*보안 코파일럿 AI가 생성한 보고서*
*신뢰도: {confidence}%*
""",
    required_fields=["incident_id", "severity", "executive_summary"],
    optional_sections=["ioc_template", "timeline_template"],
)


# Incident-specific templates
RANSOMWARE_TEMPLATE_EN = SummaryTemplate(
    name="Ransomware Incident Report",
    template_type=TemplateType.INCIDENT_RESPONSE,
    incident_category=IncidentCategory.RANSOMWARE,
    language="en",
    header_template="""
# RANSOMWARE INCIDENT REPORT
**CRITICAL - IMMEDIATE RESPONSE REQUIRED**

**Incident ID:** {incident_id}
**Detection Time:** {detection_time}
**Ransomware Family:** {ransomware_family}
""",
    executive_summary_template="""
## Situation Summary

{executive_summary}

**Encryption Status:**
- Encrypted Systems: {encrypted_count}
- Ransom Demand: {ransom_amount}
- Payment Deadline: {deadline}
""",
    detailed_summary_template="""
## Technical Analysis

### Initial Access Vector
{initial_access}

### Encryption Details
{encryption_details}

### Lateral Movement
{lateral_movement}

### Data Exfiltration Assessment
{exfiltration_status}
""",
    findings_template="""
## Critical Findings

{findings_list}

### Affected Assets
{affected_assets}
""",
    ioc_template="""
## Ransomware IOCs

### Ransomware Indicators
{ransomware_iocs}

### C2 Infrastructure
{c2_indicators}

### Encrypted File Extensions
{file_extensions}
""",
    timeline_template="""
## Attack Timeline

{timeline_entries}
""",
    recommendations_template="""
## Immediate Response Actions

### DO NOT
- Do not pay the ransom without consulting legal and security teams
- Do not delete encrypted files
- Do not shut down systems abruptly

### IMMEDIATE ACTIONS
{immediate_actions}

### RECOVERY STEPS
{recovery_steps}

### PREVENTION
{prevention_measures}
""",
    required_fields=["incident_id", "ransomware_family", "encrypted_count"],
)


class TemplateManager:
    """Manages summary templates."""

    def __init__(self) -> None:
        """Initialize template manager."""
        self._templates: dict[str, SummaryTemplate] = {}
        self._load_default_templates()

    def _load_default_templates(self) -> None:
        """Load default templates."""
        # English templates
        self._templates["executive_en"] = EXECUTIVE_TEMPLATE_EN
        self._templates["technical_en"] = TECHNICAL_TEMPLATE_EN
        self._templates["ransomware_en"] = RANSOMWARE_TEMPLATE_EN

        # Korean templates
        self._templates["executive_ko"] = EXECUTIVE_TEMPLATE_KO

    def get_template(
        self,
        template_type: TemplateType,
        incident_category: IncidentCategory = IncidentCategory.GENERAL,
        language: str = "en",
    ) -> SummaryTemplate:
        """Get appropriate template.

        Args:
            template_type: Type of template needed
            incident_category: Category of incident
            language: Desired language

        Returns:
            Matching template
        """
        # Try specific category first
        key = f"{incident_category.value}_{language}"
        if key in self._templates:
            return self._templates[key]

        # Fall back to general template for type
        key = f"{template_type.value}_{language}"
        if key in self._templates:
            return self._templates[key]

        # Fall back to English
        key = f"{template_type.value}_en"
        if key in self._templates:
            return self._templates[key]

        # Return executive as default
        return EXECUTIVE_TEMPLATE_EN

    def register_template(self, key: str, template: SummaryTemplate) -> None:
        """Register a custom template.

        Args:
            key: Template key
            template: Template to register
        """
        self._templates[key] = template

    def list_templates(self) -> list[str]:
        """List available template keys."""
        return list(self._templates.keys())

    def render(
        self,
        template: SummaryTemplate,
        data: dict[str, Any],
        sections: list[str] | None = None,
    ) -> str:
        """Render a template with data.

        Args:
            template: Template to render
            data: Data to fill template
            sections: Specific sections to include (None = all)

        Returns:
            Rendered template string
        """
        output = []

        # Header
        output.append(self._render_section(template.header_template, data))

        # Executive summary
        if not sections or "executive_summary" in sections:
            output.append(self._render_section(template.executive_summary_template, data))

        # Detailed summary
        if not sections or "detailed_summary" in sections:
            output.append(self._render_section(template.detailed_summary_template, data))

        # Findings
        if not sections or "findings" in sections:
            output.append(self._render_section(template.findings_template, data))

        # IOCs
        if (not sections or "ioc" in sections) and "ioc_template" not in template.optional_sections:
            output.append(self._render_section(template.ioc_template, data))

        # Timeline
        if (not sections or "timeline" in sections) and "timeline_template" not in template.optional_sections:
            output.append(self._render_section(template.timeline_template, data))

        # Recommendations
        if not sections or "recommendations" in sections:
            output.append(self._render_section(template.recommendations_template, data))

        # Footer
        if template.footer_template:
            output.append(self._render_section(template.footer_template, data))

        return "\n".join(output)

    def _render_section(self, template_str: str, data: dict[str, Any]) -> str:
        """Render a template section."""
        try:
            # Handle list fields
            processed_data = {}
            for key, value in data.items():
                if isinstance(value, list):
                    if key.endswith("_list"):
                        processed_data[key] = "\n".join(f"- {item}" for item in value)
                    elif key.endswith("_table"):
                        processed_data[key] = "\n".join(
                            f"| {item.get('type', '')} | {item.get('value', '')} | {item.get('context', '')} |"
                            for item in value if isinstance(item, dict)
                        )
                    else:
                        processed_data[key] = ", ".join(str(v) for v in value)
                else:
                    processed_data[key] = value

            # Fill template
            return template_str.format_map(SafeDict(processed_data))
        except Exception as e:
            return f"[Template rendering error: {e}]"


class SafeDict(dict):
    """Dict that returns placeholder for missing keys."""

    def __missing__(self, key: str) -> str:
        return f"[{key}]"


def format_findings_list(findings: list[dict[str, Any]]) -> str:
    """Format findings list for template."""
    lines = []
    for i, finding in enumerate(findings, 1):
        severity = finding.get("severity", "").upper()
        title = finding.get("title", "")
        description = finding.get("description", "")
        lines.append(f"**{i}. [{severity}] {title}**")
        lines.append(f"   {description}")
        lines.append("")
    return "\n".join(lines)


def format_timeline_entries(timeline: list[dict[str, Any]]) -> str:
    """Format timeline entries for template."""
    lines = []
    for entry in timeline:
        timestamp = entry.get("timestamp", "Unknown")
        event_type = entry.get("event_type", "")
        description = entry.get("description", "")
        lines.append(f"- **{timestamp}** - {event_type}")
        if description:
            lines.append(f"  {description}")
    return "\n".join(lines)


def format_ioc_table(iocs: list[dict[str, Any]]) -> str:
    """Format IOC table for template."""
    lines = []
    for ioc in iocs:
        ioc_type = ioc.get("type", "")
        value = ioc.get("value", "")
        context = ioc.get("context", "")[:50]
        lines.append(f"| {ioc_type} | `{value}` | {context} |")
    return "\n".join(lines)
