-- ============================================================================
-- SIEM-SOAR Platform: Alerts Table Schema
-- ============================================================================
-- Table: siem.alerts
-- Purpose: Security alerts generated by detection rules and ML models
-- Engine: ReplicatedMergeTree for HA
-- Partitioning: Daily by created_at
-- TTL: 365 days (alerts retained longer than raw events)
-- ============================================================================

CREATE TABLE IF NOT EXISTS siem.alerts ON CLUSTER '{cluster}'
(
    -- ========================================================================
    -- Core Identity
    -- ========================================================================
    alert_id                        UUID DEFAULT generateUUIDv4(),
    tenant_id                       String,

    -- ========================================================================
    -- Timestamps
    -- ========================================================================
    created_at                      DateTime64(3, 'UTC') DEFAULT now64(3),
    updated_at                      DateTime64(3, 'UTC') DEFAULT now64(3),
    first_event_time                DateTime64(3, 'UTC'),
    last_event_time                 DateTime64(3, 'UTC'),

    -- ========================================================================
    -- Alert Classification
    -- ========================================================================
    alert_name                      String,
    alert_description               String DEFAULT '',
    alert_type                      Enum8(
                                        'UNKNOWN' = 0,
                                        'DETECTION_RULE' = 1,
                                        'ML_ANOMALY' = 2,
                                        'CORRELATION' = 3,
                                        'IOC_MATCH' = 4,
                                        'BEHAVIOR' = 5,
                                        'THREAT_INTEL' = 6,
                                        'COMPLIANCE' = 7,
                                        'CUSTOM' = 8
                                    ) DEFAULT 'UNKNOWN',

    -- ========================================================================
    -- Severity & Priority
    -- ========================================================================
    severity                        Enum8(
                                        'UNKNOWN' = 0,
                                        'INFORMATIONAL' = 1,
                                        'LOW' = 2,
                                        'MEDIUM' = 3,
                                        'HIGH' = 4,
                                        'CRITICAL' = 5
                                    ) DEFAULT 'MEDIUM',
    priority                        UInt8 DEFAULT 50,  -- 0-100 scale
    confidence                      Float32 DEFAULT 0.5,  -- 0.0-1.0
    risk_score                      Float32 DEFAULT 0,  -- Computed risk score

    -- ========================================================================
    -- Alert State & Workflow
    -- ========================================================================
    status                          Enum8(
                                        'OPEN' = 0,
                                        'TRIAGED' = 1,
                                        'IN_PROGRESS' = 2,
                                        'PENDING' = 3,
                                        'RESOLVED' = 4,
                                        'CLOSED' = 5
                                    ) DEFAULT 'OPEN',
    resolution                      Enum8(
                                        'NONE' = 0,
                                        'TRUE_POSITIVE' = 1,
                                        'FALSE_POSITIVE' = 2,
                                        'BENIGN' = 3,
                                        'DUPLICATE' = 4,
                                        'MITIGATED' = 5,
                                        'NOT_APPLICABLE' = 6
                                    ) DEFAULT 'NONE',
    assignee_id                     String DEFAULT '',
    assignee_name                   String DEFAULT '',

    -- ========================================================================
    -- Detection Source
    -- ========================================================================
    rule_id                         String DEFAULT '',
    rule_name                       String DEFAULT '',
    rule_type                       Enum8(
                                        'UNKNOWN' = 0,
                                        'SIGMA' = 1,
                                        'YARA' = 2,
                                        'CUSTOM' = 3,
                                        'ML' = 4,
                                        'CORRELATION' = 5,
                                        'IOC' = 6
                                    ) DEFAULT 'UNKNOWN',
    rule_version                    String DEFAULT '',
    rule_tags                       Array(String),

    -- ML Model Info (for ML-based alerts)
    model_id                        String DEFAULT '',
    model_name                      String DEFAULT '',
    model_version                   String DEFAULT '',
    model_explanation               String DEFAULT '',

    -- ========================================================================
    -- Affected Entities
    -- ========================================================================
    -- Principal (Source/Actor)
    principal_hostname              String DEFAULT '',
    principal_ip                    Array(IPv6),
    principal_user_id               String DEFAULT '',
    principal_user_name             String DEFAULT '',
    principal_asset_id              String DEFAULT '',
    principal_asset_type            LowCardinality(String) DEFAULT '',
    principal_asset_criticality     UInt8 DEFAULT 0,

    -- Target (Destination)
    target_hostname                 String DEFAULT '',
    target_ip                       Array(IPv6),
    target_user_id                  String DEFAULT '',
    target_user_name                String DEFAULT '',
    target_asset_id                 String DEFAULT '',
    target_asset_type               LowCardinality(String) DEFAULT '',
    target_asset_criticality        UInt8 DEFAULT 0,
    target_url                      String DEFAULT '',
    target_file_path                String DEFAULT '',
    target_file_sha256              FixedString(64) DEFAULT '',

    -- ========================================================================
    -- Related Events
    -- ========================================================================
    event_count                     UInt64 DEFAULT 1,
    event_ids                       Array(UUID),  -- Related event IDs
    sample_events                   String DEFAULT '' CODEC(ZSTD(3)),  -- JSON array of sample events

    -- ========================================================================
    -- MITRE ATT&CK Mapping
    -- ========================================================================
    mitre_tactics                   Array(LowCardinality(String)),
    mitre_techniques                Array(LowCardinality(String)),
    mitre_sub_techniques            Array(LowCardinality(String)),

    -- ========================================================================
    -- Threat Intelligence
    -- ========================================================================
    ti_matched                      UInt8 DEFAULT 0,
    ti_ioc_values                   Array(String),
    ti_ioc_types                    Array(String),
    ti_feed_names                   Array(String),
    ti_threat_actors                Array(String),
    ti_malware_families             Array(String),
    ti_campaigns                    Array(String),

    -- ========================================================================
    -- Case Management
    -- ========================================================================
    case_id                         UUID DEFAULT toUUID('00000000-0000-0000-0000-000000000000'),
    case_name                       String DEFAULT '',
    incident_id                     String DEFAULT '',

    -- ========================================================================
    -- Playbook & Response
    -- ========================================================================
    playbook_ids                    Array(String),
    playbook_execution_ids          Array(String),
    response_actions_taken          Array(String),
    containment_status              Enum8(
                                        'NONE' = 0,
                                        'PENDING' = 1,
                                        'IN_PROGRESS' = 2,
                                        'CONTAINED' = 3,
                                        'FAILED' = 4
                                    ) DEFAULT 'NONE',

    -- ========================================================================
    -- AI Triage
    -- ========================================================================
    ai_triage_score                 Float32 DEFAULT 0,
    ai_triage_label                 Enum8(
                                        'UNKNOWN' = 0,
                                        'TRUE_POSITIVE' = 1,
                                        'LIKELY_TRUE_POSITIVE' = 2,
                                        'NEEDS_REVIEW' = 3,
                                        'LIKELY_FALSE_POSITIVE' = 4,
                                        'FALSE_POSITIVE' = 5
                                    ) DEFAULT 'UNKNOWN',
    ai_triage_explanation           String DEFAULT '',
    ai_suggested_actions            Array(String),
    ai_similar_alerts               Array(UUID),

    -- ========================================================================
    -- Timeline & SLA
    -- ========================================================================
    first_seen_at                   DateTime64(3, 'UTC') DEFAULT now64(3),
    last_seen_at                    DateTime64(3, 'UTC') DEFAULT now64(3),
    acknowledged_at                 DateTime64(3, 'UTC') DEFAULT toDateTime64(0, 3),
    resolved_at                     DateTime64(3, 'UTC') DEFAULT toDateTime64(0, 3),
    sla_breach_at                   DateTime64(3, 'UTC') DEFAULT toDateTime64(0, 3),
    sla_breached                    UInt8 DEFAULT 0,

    -- ========================================================================
    -- Notes & Comments
    -- ========================================================================
    analyst_notes                   String DEFAULT '' CODEC(ZSTD(3)),
    comment_count                   UInt32 DEFAULT 0,

    -- ========================================================================
    -- Tags & Labels
    -- ========================================================================
    tags                            Array(String),
    labels                          Map(String, String),

    -- ========================================================================
    -- External References
    -- ========================================================================
    external_ticket_id              String DEFAULT '',
    external_ticket_url             String DEFAULT '',
    url_back_to_product             String DEFAULT '',

    -- ========================================================================
    -- Data Source
    -- ========================================================================
    source_vendor                   LowCardinality(String) DEFAULT '',
    source_product                  LowCardinality(String) DEFAULT '',
    source_log_types                Array(String),

    -- ========================================================================
    -- Version Control (for optimistic locking)
    -- ========================================================================
    version                         UInt64 DEFAULT 1
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/siem/alerts', '{replica}')
PARTITION BY toYYYYMMDD(created_at)
ORDER BY (tenant_id, severity, status, created_at, sipHash64(alert_id))
TTL created_at + INTERVAL 365 DAY DELETE
SETTINGS
    index_granularity = 8192,
    min_bytes_for_wide_part = 10485760,
    ttl_only_drop_parts = 1;

-- ============================================================================
-- Secondary Indexes
-- ============================================================================

-- Status Index (for filtering by alert state)
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_status status TYPE set(10) GRANULARITY 4;

-- Resolution Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_resolution resolution TYPE set(10) GRANULARITY 4;

-- Severity Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_severity severity TYPE set(10) GRANULARITY 4;

-- Alert Type Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_alert_type alert_type TYPE set(20) GRANULARITY 4;

-- Principal IP Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_principal_ip principal_ip TYPE bloom_filter GRANULARITY 4;

-- Target IP Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_target_ip target_ip TYPE bloom_filter GRANULARITY 4;

-- Rule ID Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_rule_id rule_id TYPE bloom_filter GRANULARITY 4;

-- Case ID Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_case_id case_id TYPE bloom_filter GRANULARITY 4;

-- Assignee Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_assignee assignee_id TYPE bloom_filter GRANULARITY 4;

-- AI Triage Label Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_ai_triage ai_triage_label TYPE set(10) GRANULARITY 4;

-- Alert Name Index (Token search)
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_alert_name alert_name TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 4;

-- MITRE Tactics Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_mitre_tactics mitre_tactics TYPE bloom_filter GRANULARITY 4;

-- MITRE Techniques Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_mitre_techniques mitre_techniques TYPE bloom_filter GRANULARITY 4;

-- Tags Index
ALTER TABLE siem.alerts ON CLUSTER '{cluster}'
    ADD INDEX idx_tags tags TYPE bloom_filter GRANULARITY 4;

-- ============================================================================
-- Distributed Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS siem.alerts_distributed ON CLUSTER '{cluster}'
AS siem.alerts
ENGINE = Distributed('{cluster}', 'siem', 'alerts', rand());

-- ============================================================================
-- Alert Count Aggregation View
-- ============================================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS siem.alerts_hourly_mv ON CLUSTER '{cluster}'
TO siem.alerts_hourly
AS SELECT
    tenant_id,
    toStartOfHour(created_at) AS hour,
    severity,
    status,
    alert_type,
    rule_id,
    count() AS alert_count,
    uniq(principal_hostname) AS unique_hosts,
    uniq(principal_user_id) AS unique_users,
    avg(ai_triage_score) AS avg_ai_score
FROM siem.alerts
GROUP BY tenant_id, hour, severity, status, alert_type, rule_id;

-- Destination table for the materialized view
CREATE TABLE IF NOT EXISTS siem.alerts_hourly ON CLUSTER '{cluster}'
(
    tenant_id                       String,
    hour                            DateTime,
    severity                        Enum8(
                                        'UNKNOWN' = 0,
                                        'INFORMATIONAL' = 1,
                                        'LOW' = 2,
                                        'MEDIUM' = 3,
                                        'HIGH' = 4,
                                        'CRITICAL' = 5
                                    ),
    status                          Enum8(
                                        'OPEN' = 0,
                                        'TRIAGED' = 1,
                                        'IN_PROGRESS' = 2,
                                        'PENDING' = 3,
                                        'RESOLVED' = 4,
                                        'CLOSED' = 5
                                    ),
    alert_type                      Enum8(
                                        'UNKNOWN' = 0,
                                        'DETECTION_RULE' = 1,
                                        'ML_ANOMALY' = 2,
                                        'CORRELATION' = 3,
                                        'IOC_MATCH' = 4,
                                        'BEHAVIOR' = 5,
                                        'THREAT_INTEL' = 6,
                                        'COMPLIANCE' = 7,
                                        'CUSTOM' = 8
                                    ),
    rule_id                         String,
    alert_count                     UInt64,
    unique_hosts                    UInt64,
    unique_users                    UInt64,
    avg_ai_score                    Float32
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/siem/alerts_hourly', '{replica}')
PARTITION BY toYYYYMM(hour)
ORDER BY (tenant_id, hour, severity, status, alert_type, rule_id)
TTL hour + INTERVAL 2 YEAR DELETE;

-- ============================================================================
-- Comments
-- ============================================================================
-- Alert lifecycle:
-- 1. Alert created (status = OPEN)
-- 2. AI triage assigns score and label
-- 3. Analyst acknowledges (status = TRIAGED)
-- 4. Investigation begins (status = IN_PROGRESS)
-- 5. Resolution set (resolution = TRUE_POSITIVE/FALSE_POSITIVE/etc.)
-- 6. Alert closed (status = CLOSED/RESOLVED)
--
-- SLA calculation:
-- sla_breach_at is set based on severity:
--   CRITICAL: 15 minutes
--   HIGH: 1 hour
--   MEDIUM: 4 hours
--   LOW: 24 hours
