# Sealed Secrets Configuration for SIEM-SOAR Platform
# Uses Bitnami Sealed Secrets controller

---
# Namespace for secrets
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
# HelmRelease for Sealed Secrets (if using Flux)
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:
    fullnameOverride: sealed-secrets-controller
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
---
# Example SealedSecret template for database credentials
# Seal using: kubeseal --format yaml < secret.yaml > sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-secret
  namespace: siem-data
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    password: AgXXX...  # Sealed password
  template:
    metadata:
      name: clickhouse-secret
      namespace: siem-data
      labels:
        app.kubernetes.io/part-of: siem-soar-platform
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: siem-data
spec:
  encryptedData:
    password: AgXXX...  # Sealed password
  template:
    metadata:
      name: postgresql-secret
      namespace: siem-data
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: siem-data
spec:
  encryptedData:
    password: AgXXX...  # Sealed password
  template:
    metadata:
      name: redis-secret
      namespace: siem-data
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gateway-jwt-secret
  namespace: siem-services
spec:
  encryptedData:
    public-key: AgXXX...  # Sealed JWT public key
    private-key: AgXXX...  # Sealed JWT private key
  template:
    metadata:
      name: gateway-jwt-secret
      namespace: siem-services
    type: Opaque
---
# Instructions for sealing secrets:
# 1. Install kubeseal CLI
# 2. Fetch the public key:
#    kubeseal --fetch-cert > pub-sealed-secrets.pem
# 3. Create a secret YAML file (secret.yaml):
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: my-secret
#      namespace: my-namespace
#    type: Opaque
#    data:
#      password: base64encodedpassword
# 4. Seal it:
#    kubeseal --format yaml < secret.yaml > sealed-secret.yaml
# 5. Apply the sealed secret:
#    kubectl apply -f sealed-secret.yaml
